[project]
name = "agnos"
version = "0.1.0"
authors = [{name = "Vehicle Researcher", email = "user@comma.ai"}]
requires-python = ">=3.12.3, <3.13"
description = ""
dependencies = [
  "openpilot",
  "openpilot[tools,testing]",
  "tinymesa==25.2.7.2",

  "pycapnp==2.1.0",  # 2.2 introduces a memory leak due to cyclic references
  "comma-deps-eigen",
  "cython",
  "libdatachannel-py>=2026.1.0.dev2",
  "pycryptodome",
  "setuptools",
  "spidev",

  # hardware.py
  "dbus-python",
  # amplifier.py
  "smbus2",

  # provisioning
  "pyusb",
  # pandad
  "libusb1 ==3.1.0", # recent versions segfault on comma three
  "paramiko",

  # extra nice-to-haves
  "evdev",
  "ipython",
  "py-spy",
  "spidev2",
  "flaky",
  "matplotlib",

  # GUIs
  "comma-deps-raylib",
]

[tool.uv.sources]
openpilot = { path = "openpilot" }
