#!/bin/sh
# rmt_storage - Remote storage for modem
exec 2>&1

# Wait for block devices
for dev in modemst1 modemst2 fsc fsg; do
  /usr/comma/wait_for_file.sh /dev/block/bootdevice/by-name/$dev
done

exec /usr/sbin/rmt_storage
