#!/bin/sh
#
#    10-header - create the header of the MOTD

# Source os-release for PRETTY_NAME (works on Void, Ubuntu, etc.)
[ -r /etc/os-release ] && . /etc/os-release

AGNOS_DESCRIPTION=$(cat /VERSION)

# For CI builds e.g. "11-ade422a"
case "$AGNOS_DESCRIPTION" in
	*-*) AGNOS_DESCRIPTION="${AGNOS_DESCRIPTION%-*} (${AGNOS_DESCRIPTION#*-})" ;;
esac

printf "Welcome to AGNOS v%s\n" "$AGNOS_DESCRIPTION"
printf "Based on %s (%s %s %s)\n" "$PRETTY_NAME" "$(uname -o)" "$(uname -r)" "$(uname -m)"
