FROM ubuntu:24.04

# Set non-interactive installation
ENV DEBIAN_FRONTEND=noninteractive

# Update and install necessary packages
RUN apt-get update && \
    apt-get install -y android-sdk-libsparse-utils && \
    rm -rf /var/lib/apt/lists/*

# Set entrypoint to keep container running
ENTRYPOINT ["tail", "-f", "/dev/null"]
