pcm.!default {
	type empty
	slave.pcm {
		@func refer
		name {
			@func concat
			strings [
				"pcm.comma_default_"
				{
					@func card_id
					card 0
				}
			]
		}
		default {
			type plug
			slave.pcm {
				type hw
				card 0
			}
		}
	}
}

pcm.comma_default_commamici {
	type asym
	playback.pcm "plughw:0,0"
	capture.pcm "plughw:0,1"
}
