#!/usr/bin/env bash
set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
ROOT=$DIR/../

# just a nice wrapper around the edl python tool

EDL_PATH=$DIR/edl_repo
VERSION="8573eba1b576305fec3a068393283143ffc34342"

if [ ! -d "$EDL_PATH" ]; then
  rm -rf $EDL_PATH
  git clone https://github.com/bkerler/edl $EDL_PATH
fi

pushd $EDL_PATH > /dev/null
python3 -m venv venv
source venv/bin/activate

if [ "$(< .git/HEAD)" != "$VERSION" ]; then
  echo "updating edl..."
  git fetch origin $VERSION
  git checkout $VERSION
  git submodule update --depth=1 --init --recursive

  # TODO: remove "--no-binary capstone" when capstone v5.0.2 is released
  # https://github.com/capstone-engine/capstone/issues/2301#issuecomment-2026835275
  pip3 install -r requirements.txt --no-binary capstone
fi
popd > /dev/null

$EDL_PATH/edl "$@"

################################################################################
# On M-series macs, if you get "No backend available"
# where python is installed with pyenv and libusb with brew
# try this:
#
# brew install libusb
# sudo mkdir -p /usr/local/lib
# sudo ln -s /opt/homebrew/lib/libusb-1.0.0.dylib /usr/local/lib/libusb.dylib
#
################################################################################
