#!/bin/sh
#
# Copyright (c) 2017, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived from
#       this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE DISCLAIMED.  IN NO
# EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# DESCRIPTION:  DIAG + ADB + MBIM + GNSS + DUN

echo "Switching to composition number 0x90D5" > /dev/kmsg

if [ "$1" = "y" ]; then
	num="1"
	mode="hsic"
else
	num="0"
	mode="hsusb"
fi

if [ "$#" -ge 2 ]; then
	delay=$2
else
	delay="0"
fi

if [ "$#" -ge 3 ]; then
	from_adb=$3
else
	from_adb="n"
fi

run_9650() {
	if [ $from_adb = "n" ]
	then
		pkill adbd
	fi
	echo 0 > /sys/class/android_usb/android$num/enable
	echo 90D5 > /sys/class/android_usb/android$num/idProduct
	echo 05C6 > /sys/class/android_usb/android$num/idVendor
	echo 239 > /sys/class/android_usb/android$num/bDeviceClass
	echo 2 > /sys/class/android_usb/android$num/bDeviceSubClass
	echo 1 > /sys/class/android_usb/android$num/bDeviceProtocol
	echo diag > /sys/class/android_usb/android0/f_diag/clients
	echo smd > /sys/class/android_usb/android0/f_serial/transports
	echo diag,ffs,mbim_gsi,gps,serial > /sys/class/android_usb/android$num/functions
	echo 1 > /sys/class/android_usb/android$num/remote_wakeup
	sleep $delay
	echo 1 > /sys/class/android_usb/android$num/enable
	if [ $from_adb = "n" ]
	then
		/etc/init.d/adbd start
	fi
}

run_sdx20() {
	if [ $from_adb = "n" ]
	then
		pkill adbd
	fi
	echo 0 > /sys/class/android_usb/android$num/enable
	echo 90D5 > /sys/class/android_usb/android$num/idProduct
	echo 05C6 > /sys/class/android_usb/android$num/idVendor
	echo 239 > /sys/class/android_usb/android$num/bDeviceClass
	echo 2 > /sys/class/android_usb/android$num/bDeviceSubClass
	echo 1 > /sys/class/android_usb/android$num/bDeviceProtocol
	echo diag > /sys/class/android_usb/android0/f_diag/clients
	echo char_bridge > /sys/class/android_usb/android0/f_serial/transports
	echo glink >  /sys/class/android_usb/android$num/f_gps/transport
	echo diag,ffs,mbim_gsi,gps,serial > /sys/class/android_usb/android$num/functions
	echo 1 > /sys/class/android_usb/android$num/remote_wakeup
	sleep $delay
	echo 1 > /sys/class/android_usb/android$num/enable
	if [ $from_adb = "n" ]
	then
		/etc/init.d/adbd start
	fi
}

run_configfs() {
	if [ $from_adb = "n" ]
	then
		pkill adbd
		/etc/launch_adbd start
		sleep 1
	fi
	cd /sys/kernel/config/usb_gadget/g1
	rm configs/c*/f* 2> /dev/null
	rm -rf configs/c.2 configs/c.3 2> /dev/null
	echo 0x05c6 > idVendor
	echo 0x90D5 > idProduct
	echo 239 > bDeviceClass
	echo 2 > bDeviceSubClass
	echo 1 > bDeviceProtocol
	echo "DIAG_ADB_MBIM_GNSS_DUN" > configs/c.1/strings/0x409/configuration
	ln -s functions/diag.diag configs/c.1/f1
	ln -s functions/ffs.adb configs/c.1/f2
	ln -s functions/gsi.mbim configs/c.1/f3
	ln -s functions/gsi.gps configs/c.1/f4
	ln -s functions/cser.dun.0 configs/c.1/f5
	echo 0xA0 > configs/c.1/bmAttributes
	echo "binding UDC with Gadget..." $1
	echo $1 > UDC
	cd /
}

case `source /sbin/usb/target` in
	*9650* )
		run_9650 &
		;;
	*sdx20* )
		run_sdx20 &
		;;
	*sdxpoorwills* )
		udcname=`ls -1 /sys/class/udc | head -n 1`
		run_configfs $udcname &
		;;
	* )
		echo "This composition is not supported"
		;;
esac

