manufacturer = comma.ai
product = Linux USB Gadget
serial = 0x1234

[MTP]
usb_max_packet_len = 512
usb_functionfs_path = /dev/usb-ffs/mtp

[STORAGE]
name = Recordings
storage = /data/media/0/realdata
