name: tests
on:
  push:
  pull_request:

jobs:
  precommit:
    name: pre-commit
    runs-on: ubuntu-20.04
    timeout-minutes: 8
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - run: 'pip install pre-commit'
    - run: 'pre-commit run --all'
